# Updated DVC

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    outs:
      - data/preprocessed_data.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/preprocessed_data.csv
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed
    params:
      - feature_engineering.test_size
      - feature_engineering.random_state
    outs:
      - data/interim

  model_building:
    cmd: python src/models/model_building.py
    deps:
      - src/models/model_building.py
      - data/interim
    params:
      - model_building.n_estimators
    outs:
      - models/random_forest_model.pkl

  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
      - src/models/model_evaluation.py
      - models/random_forest_model.pkl
    metrics:
      - reports/metrics.json
    outs:
      - reports/model_metrics.json

  

  